### ISSUE TITLE
Utils don't work for enums in lowercase

### ISSUE THREAD

**Issue by feliperenan** [coingaming/gen_enum#2]
I saw that this library always transform string to uppercase in order to fetch its Enum value and the documentation itself uses only atoms in uppercase.

https://github.com/coingaming/gen_enum/blob/25535dc12a340e57f95d5fe3e69873c7ae8c63e6/lib/gen_enum.ex#L270

Is this supposed to work with lowercase atoms? If so, this is a bug. Otherwise, we should update the documentation to indicate that somehow.

### Steps to reproduce

```Elixir
iex> require GenEnum
GenEnum
iex> GenEnum.defenum(module: OS, database_type: :os, values: [:linux, :mac, :windows])
iex> require OS.Utils
iex> OS.Utils.to_enum "mac"
{:error, "can not convert value to Elixir.OS, got invalid string from: \"mac\""}
```

**Comment by tim2CF** [comment]
@feliperenan good catch! Definitely it was a bug, fixed in `0.4.2`, pushed to hex.
